port: 5555 #An optional port defaults to 0 if not present
# The folder path to store all items.
# Secrets will be stored at <path>/secrets.json
# Messages at <path>/messages.txt
# Files at <path>/nameoffile
## If "default" is passed, the folder path will be `share`'s directory in the machine's local folder.
save_path: "default"
secret: #Optional during receive
- key: foo
  value: bar
- key: baz
  value: woo
message: #Optional during receive
- new message from me
- test message
file: #Optional during receive
- "./dev_build.sh"
debug: 0 #Compulsory. 0 is for off and 1 and above for on

